version: 0.0
os: windows

files:
  - source: publish
    destination: C:\inetpub\wwwroot\PramodApi

hooks:
  BeforeInstall:
    - location: scripts/before_install.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts/after_install.ps1
      timeout: 300
      runas: Administrator

  ApplicationStart:
    - location: scripts/start_server.ps1
      timeout: 300
      runas: Administrator